services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    restart: always
    depends_on:
      - web

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - static_volume:/djsite/static
      - media_volume:/djsite/media
    depends_on:
      - pgdb

  pgdb:
      image: postgres:17-alpine
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: pgdb
      ports:
        - 5432:5432

volumes:
  static_volume:
  media_volume: